// precios.js
export const precios = {
    '.vinos .vinos1':{sala:'21,00€', terraza:'22,10€'},
  '.vinos .vinos2':{sala:'21,00€', terraza:''},
  '.vinos .vinos3':{sala:'18,00€', terraza:''},
  '.vinos .vinos4':{sala:'15,00€', terraza:''},
  '.vinos .vinos5':{sala:'21,00€', terraza:''},
  '.vinos .vinos6':{sala:'21,00€', terraza:''},
  '.vinos .vinos7':{sala:'21,00€', terraza:''},
  '.vinos .vinos8':{sala:'15,00€', terraza:''},
  '.vinos .vinos9':{sala:'15,00€', terraza:''},
  '.vinos .vinos10':{sala:'15,00€', terraza:''},
  '.vinos .vinos11':{sala:'18,00€', terraza:''},
  '.vinos .vinos12':{sala:'18,00€', terraza:''},
  '.vinos .vinos13':{sala:'15,00€', terraza:''},
  '.vinos .vinos14':{sala:'15,00€', terraza:''},
  '.vinos .vinos15':{sala:'15,00€', terraza:''},
  '.ensaladas .ensalada1':{sala:'10,00 €', terraza:'11,00 €'},
  '.ensaladas .ensalada2':{sala:'10,00 €', terraza:''},
  '.ensaladas .ensalada3':{sala:'10,00 €', terraza:''},
  '.ensaladas .ensalada4':{sala:'11,00 €', terraza:''},
  '.arroces .arroces1':{sala:'13,00 €', terraza:''},
  '.arroces .arroces2':{sala:'13,00 €', terraza:''},
  '.carnes .carnes1':{sala:'24,00 €', terraza:''},
  '.carnes .carnes2':{sala:'32,00 €', terraza:''},
  '.carnes .carnes3':{sala:'42,00 €', terraza:''},
  '.carnes .carnes4':{sala:'19,00 €', terraza:''},
  '.carnes .carnes5':{sala:'21,00 €', terraza:''},
  '.carnes .carnes6':{sala:'14,00 €', terraza:''},
  '.carnes .carnes7':{sala:'21,00 €', terraza:''},
  '.carnes .carnes8':{sala:'12,00 €', terraza:''},
  '.carnes .carnes9':{sala:'12,00 €', terraza:''},
  '.carnes .carnes10':{sala:'21,00 €', terraza:''},
  '.pescados .pescados1':{sala:'14,00 €', terraza:''},
  '.pescados .pescados2':{sala:'16,00 €', terraza:''},
  '.pescados .pescados3':{sala:'16,00 €', terraza:''},
  '.pescados .pescados4':{sala:'16,00 €', terraza:''},
  '.croquetas .croquetas1':{sala:'9,00€', terraza:''},
  '.croquetas .croquetas2':{sala:'9,00€', terraza:''},
  '.croquetas .croquetas3':{sala:'12,00€', terraza:''},
  '.croquetas .croquetas4':{sala:'12,00€', terraza:''},
  '.croquetas .croquetas5':{sala:'12,00€', terraza:''},
  '.raciones .raciones1':{sala:'9,00€', terraza:''},
  '.raciones .raciones2':{sala:'13,00€', terraza:''},
  '.raciones .raciones3':{sala:'9,00€', terraza:''},
  '.raciones .raciones4':{sala:'9,50€', terraza:''},
  '.raciones .raciones5':{sala:'8,50€', terraza:''},
  '.raciones .raciones6':{sala:'8,50€', terraza:''},
  '.raciones .raciones7':{sala:'11,50€', terraza:''},
  '.raciones .raciones8':{sala:'6,50€', terraza:''},
  '.raciones .raciones9':{sala:'12,00€', terraza:''},
  '.raciones .raciones10':{sala:'6,50€', terraza:''},
  '.raciones .raciones11':{sala:'5,50€', terraza:''},
  '.raciones .raciones12':{sala:'5,50€', terraza:''},
  '.raciones .raciones13':{sala:'6,50€', terraza:''},
  '.raciones .raciones14':{sala:'7,00€', terraza:''},
  '.raciones .raciones15':{sala:'8,50€', terraza:''},
  '.raciones .raciones16':{sala:'9,50€', terraza:''},
  '.raciones .raciones17':{sala:'11,00€', terraza:''},
  '.raciones .raciones18':{sala:'12,00€', terraza:''},
  '.raciones .raciones19':{sala:'13,00€', terraza:''},
  '.raciones .raciones20':{sala:'9,00€', terraza:''},
  '.raciones .raciones21':{sala:'12,00€', terraza:''},
  '.baguettes .baguettes1':{sala:'5,00 €', terraza:''},
  '.baguettes .baguettes2':{sala:'5,00 €', terraza:''},
  '.baguettes .baguettes3':{sala:'6,00 €', terraza:''},
  '.baguettes .baguettes4':{sala:'5,00 €', terraza:''},
  '.baguettes .baguettes5':{sala:'5,00 €', terraza:''},
  '.baguettes .baguettes6':{sala:'5,00 €', terraza:''},
  '.baguettes .baguettes7':{sala:'6,00 €', terraza:''},
  '.baguettes .baguettes8':{sala:'6,00 €', terraza:''},
  '.baguettes .baguettes9':{sala:'6,00 €', terraza:''},
  '.baguettes .baguettes10':{sala:'6,00 €', terraza:''},
  '.sandwichs .sandwichs1':{sala:'3,00 €', terraza:''},
  '.sandwichs .sandwichs2':{sala:'4,00 €', terraza:''},
  '.sandwichs .sandwichs3':{sala:'4,50 €', terraza:''},
  '.sandwichs .sandwichs4':{sala:'6,00 €', terraza:''},
  '.tostas .tostas1':{sala:'8,00 €', terraza:''},
  '.tostas .tostas2':{sala:'8,00 €', terraza:''},
  '.tostas .tostas3':{sala:'9,50 €', terraza:''},
  '.tostas .tostas4':{sala:'10,00 €', terraza:''},
  '.tostas .tostas5':{sala:'11,00 €', terraza:''},
  '.tostas .tostas6':{sala:'10,00 €', terraza:''},
  '.tostas .tostas7':{sala:'11,00 €', terraza:''},
  '.hamburguesas .hamburguesas1':{sala:'4,00€', terraza:''},
  '.hamburguesas .hamburguesas2':{sala:'4,50€', terraza:''},
  '.hamburguesas .hamburguesas3':{sala:'5,00€', terraza:''},
  '.hamburguesas .hamburguesas4':{sala:'5,50€', terraza:''},
  '.hamburguesas .hamburguesas5':{sala:'8,00€', terraza:''},
  '.hamburguesas .hamburguesas6':{sala:'10,00€', terraza:''},
  '.hamburguesas .hamburguesas7':{sala:'11,00€', terraza:''},
  '.hamburguesas .hamburguesas8':{sala:'15,00€', terraza:''},
  '.pizzas .pizzas1':{sala:'11,00€', terraza:''},
  '.pizzas .pizzas2':{sala:'11,00€', terraza:''},
  '.pizzas .pizzas3':{sala:'11,00€', terraza:''},
  '.pizzas .pizzas4':{sala:'11,00€', terraza:''},
  '.pizzas .pizzas5':{sala:'11,00€', terraza:''},
  '.pizzas .pizzas6':{sala:'10,00€', terraza:''},
  '.pizzas .pizzas7':{sala:'11,00€', terraza:''},
  '.pizzas .pizzas8':{sala:'13,00€', terraza:''},
  '.pizzas .pizzas9':{sala:'11,00€', terraza:''},
  '.postres .postres1':{sala:'4,50€', terraza:''},
  '.postres .postres2':{sala:'4,50€', terraza:''},
  '.postres .postres3':{sala:'4,50€', terraza:''},
  '.postres .postres4':{sala:'4,50€', terraza:''},
  '.postres .postres5':{sala:'4,50€', terraza:''},
  '.postres .postres6':{sala:'4,50€', terraza:''},
  '.postres .postres7':{sala:'4,50€', terraza:''},
  '.postres .postres8':{sala:'5,00€', terraza:''},
  '.postres .postres9':{sala:'4,00€', terraza:''},
  '.postres .postres10':{sala:'5,50€', terraza:''},
  '.postres .postres11':{sala:'5,50€', terraza:''},
  '.postres .postres12':{sala:'4,50€', terraza:''},
  '.postres .postres13':{sala:'4,50€', terraza:''},
};
